version: "3.9"

services:
  backend:
    env_file:
      - .env
  db:
    image: postgres:16
    container_name: burger_db
    environment:
      POSTGRES_DB: burger_constructor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker/db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d burger_constructor"]
      interval: 5s
      timeout: 5s
      retries: 15

  app:
    build: .
    container_name: burger_backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      # --- DB ---
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/burger_constructor
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate

      # --- MAIL (Gmail SMTP) ---
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: burger.test.reset@gmail.com
      SPRING_MAIL_PASSWORD: burger2535
      APP_MAIL_FROM: burger.test.reset@gmail.com
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"

      # --- APP ---
      APP_MAIL_FROM: your_email@gmail.com
    ports:
      - "8080:8080"

volumes:
  db_data:



